import streamlit as st
import pandas as pd
import plotly.express as px

# Import your database functions
from app.data.incidents import get_all_incidents, insert_incident

st.set_page_config(page_title="Cyber Dashboard", layout="wide")

# 1. Security Check: Kick user out if not logged in
if "logged_in" not in st.session_state or not st.session_state.logged_in:
    st.warning("You must log in to view this page.")
    if st.button("Go to Login"):
        st.switch_page("Home.py")
    st.stop()

# 2. Header
st.title(f"🛡️ Security Dashboard")
st.caption(f"Logged in as: {st.session_state.username}")

# 3. View Data Section (READ)
st.subheader("Recent Cyber Incidents")
# Fetch real data from your SQLite database
df = get_all_incidents()

# Display basic metrics
col1, col2, col3 = st.columns(3)
col1.metric("Total Incidents", len(df))
col2.metric("Open Cases", len(df[df['status'] == 'Open']))
col3.metric("Critical Severity", len(df[df['severity'] == 'Critical']))

# Display the dataframe
st.dataframe(df, use_container_width=True)

st.divider()

# 4. Charts Section (Visualizations)
col_chart1, col_chart2 = st.columns(2)

with col_chart1:
    st.subheader("Incidents by Type")
    if not df.empty:
        # Count incidents by category/type
        type_counts = df['category'].value_counts().reset_index()
        type_counts.columns = ['category', 'count']

        fig = px.bar(type_counts, x='category', y='count', color='category')
        st.plotly_chart(fig, use_container_width=True)

with col_chart2:
    st.subheader("Severity Distribution")
    if not df.empty:
        fig2 = px.pie(df, names='severity', title='Severity Levels')
        st.plotly_chart(fig2, use_container_width=True)

st.divider()

# 5. Add Data Section (CREATE)
st.subheader("📝 Report New Incident")

with st.form("new_incident"):
    c1, c2 = st.columns(2)
    with c1:
        date = st.date_input("Incident Date")
        category = st.selectbox(
            "Category", ["Phishing", "Malware", "DDoS", "Ransomware", "Insider Threat"])
        severity = st.selectbox(
            "Severity", ["Low", "Medium", "High", "Critical"])
    with c2:
        status = st.selectbox(
            "Status", ["Open", "Investigating", "Resolved", "Closed"])
        desc = st.text_area("Description")

    submit_btn = st.form_submit_button("Submit Report")

    if submit_btn:
        # Call your database function
        insert_incident(
            timestamp=str(date),
            severity=severity,
            category=category,
            status=status,
            description=desc
            # incident_id is auto-generated by DB
        )
        st.success("Incident reported successfully!")
        st.rerun()  # Reload page to see the new entry in the table

# 6. Logout Button
if st.sidebar.button("Logout"):
    st.session_state.logged_in = False
    st.session_state.username = ""
    st.switch_page("Home.py")
